networks:
  hackathon-fiap:
    name: hackathon-fiap
    driver: bridge

services:
  broker-rabbitmq:
    image: rabbitmq:management
    container_name: broker-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-fiap

  db-postgres-api-patient:
    image: postgres:latest
    container_name: db-postgres-api-patient
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-fiap

  app-api-patient:
    image: welderessutti/api-patient:latest
    container_name: app-api-patient
    ports:
      - "8080:8080"
    depends_on:
      db-postgres-api-patient:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db-postgres-api-patient:5432/patient"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    networks:
      - hackathon-fiap

  db-postgres-api-diabetes-exam:
    image: postgres:latest
    container_name: db-postgres-api-diabetes-exam
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diabetes_exam
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-fiap

  app-api-diabetes-exam:
    image: welderessutti/api-diabetes-exam:latest
    container_name: app-api-diabetes-exam
    ports:
      - "8081:8080"
    depends_on:
      db-postgres-api-diabetes-exam:
        condition: service_healthy
      broker-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db-postgres-api-diabetes-exam:5432/diabetes_exam"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "broker-rabbitmq"
    networks:
      - hackathon-fiap

  db-postgres-api-diagnosis:
    image: postgres:latest
    container_name: db-postgres-api-diagnosis
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diagnosis
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - hackathon-fiap

  app-api-diagnosis:
    image: welderessutti/api-diagnosis:latest
    container_name: app-api-diagnosis
    ports:
      - "8082:8080"
    depends_on:
      db-postgres-api-diagnosis:
        condition: service_healthy
      broker-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db-postgres-api-diagnosis:5432/diagnosis"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "broker-rabbitmq"
    networks:
      - hackathon-fiap

  app-ms-scheduling:
    image: welderessutti/ms-scheduling:latest
    container_name: app-ms-scheduling
    depends_on:
      broker-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "broker-rabbitmq"
    networks:
      - hackathon-fiap

  app-ms-email:
    image: welderessutti/ms-email:latest
    container_name: app-ms-email
    depends_on:
      broker-rabbitmq:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_USERNAME: "rabbitmq"
      SPRING_RABBITMQ_PASSWORD: "rabbitmq"
      SPRING_RABBITMQ_HOST: "broker-rabbitmq"
      SPRING_MAIL_USERNAME: "${SPRING_MAIL_USERNAME}"
      SPRING_MAIL_PASSWORD: "${SPRING_MAIL_PASSWORD}"
    networks:
      - hackathon-fiap
